version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper 
    build:
      context: ./zookeeper
    volumes:
    - ./config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
    - ./data/zookeeper-1/:/tmp/zookeeper/
    ports:
    - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka: 
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports: 
    - '9092:9092'
    build: 
      context: .
    volumes:
    - ./config/kafka/server.properties:/kafka/config/server.properties
    - ./data/kafka/:/tmp/kafka-logs/
    environment: 
     - KAFKA_BROKER_ID=1
     - KAFKA_ADVERTISED_HOST_NAME:localhost
     - KAFKA_LISTENERS=PLAINTEXT://:9092
     - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://127.0.0.1:9092
     - KAFKA_ZOOKEEPER_CONNECT:zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_CREATE_TOPICS:“Ecommerce:1”
    depends_on:
     - zookeeper